"""added product table from opencart database to fix the problem products is having

Revision ID: 40293f36f627
Revises: d3b2b2b08333
Create Date: 2023-02-21 09:49:37.281756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '40293f36f627'
down_revision = 'd3b2b2b08333'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('upc', sa.String(length=12), nullable=False),
    sa.Column('ean', sa.String(length=14), nullable=False),
    sa.Column('jan', sa.String(length=13), nullable=False),
    sa.Column('isbn', sa.String(length=17), nullable=False),
    sa.Column('mpn', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('stock_status_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.Column('shipping', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('price', sa.Float(precision=15, asdecimal=4), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('tax_class_id', sa.Integer(), nullable=False),
    sa.Column('date_available', sa.DateTime(), nullable=False),
    sa.Column('weight', sa.Float(precision=15, asdecimal=8), nullable=False),
    sa.Column('weight_class_id', sa.Integer(), nullable=False),
    sa.Column('length', sa.Float(precision=15, asdecimal=8), nullable=False),
    sa.Column('width', sa.Float(precision=15, asdecimal=8), nullable=False),
    sa.Column('height', sa.Float(precision=15, asdecimal=8), nullable=False),
    sa.Column('length_class_id', sa.Integer(), nullable=False),
    sa.Column('subtract', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('minimum', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('viewed', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('date_modified', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
