"""Introducing opencart database

Revision ID: 405d0cbb45e4
Revises: 40293f36f627
Create Date: 2023-02-21 21:14:18.088102

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '405d0cbb45e4'
down_revision = '40293f36f627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('customer_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('firstname', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('lastname', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('company', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('address_1', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('address_2', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('city', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('postcode', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('country_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('zone_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('custom_field', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advertise_google_target',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('store_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('campaign_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('country', mysql.VARCHAR(length=2), nullable=False),
    sa.Column('budget', mysql.DECIMAL(precision=15, scale=4), nullable=False),
    sa.Column('feeds', mysql.TEXT(), nullable=False),
    sa.Column('status', mysql.ENUM('paused', 'active'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('key', mysql.TEXT(), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=False),
    sa.Column('date_modified', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_ip',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('api_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('ip', mysql.VARCHAR(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', 'api_id')
    )
    op.create_table('api_session',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('api_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('session_id', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('ip', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=False),
    sa.Column('date_modified', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('api_id')
    )
    op.create_table('attribute',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('attribute_group_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('sort_order', mysql.INTEGER(display_width=3), nullable=False),
    sa.PrimaryKeyConstraint('attribute_group_id')
    )
    op.create_table('attribute_description',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('language_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', 'language_id')
    )
    op.create_table('attribute_group',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('sort_order', mysql.INTEGER(display_width=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attribute_group_description',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('language_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', 'language_id')
    )
    op.create_table('banner',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('banner_image',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('banner_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('language_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('link', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('image', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('sort_order', mysql.INTEGER(display_width=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('image', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('parent_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('top', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('column', mysql.INTEGER(display_width=3), nullable=False),
    sa.Column('sort_order', mysql.INTEGER(display_width=3), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=False),
    sa.Column('date_modified', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_description',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('language_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('meta_title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('meta_description', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('meta_keyword', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_filter',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('filter_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_path',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('path_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('level', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_to_google_product_category',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('google_product_category', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('store_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('category_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_to_layout',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('store_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('layout_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_to_store',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('store_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('country',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('iso_code_2', mysql.VARCHAR(length=2), nullable=False),
    sa.Column('iso_code_3', mysql.VARCHAR(length=3), nullable=False),
    sa.Column('address_format', mysql.TEXT(), nullable=False),
    sa.Column('postcode_required', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coupon',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('type', mysql.CHAR(length=1), nullable=False),
    sa.Column('discount', mysql.DECIMAL(precision=15, scale=4), nullable=False),
    sa.Column('logged', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('shipping', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('total', mysql.DECIMAL(precision=15, scale=4), nullable=False),
    sa.Column('date_start', mysql.DATETIME(), nullable=False),
    sa.Column('date_end', mysql.DATETIME(), nullable=False),
    sa.Column('uses_total', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('uses_customer', mysql.VARCHAR(length=11), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coupon_category',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('category_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('id', 'category_id')
    )
    op.create_table('coupon_history',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('coupon_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('order_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('customer_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('amount', mysql.DECIMAL(precision=15, scale=4), nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'coupon_id', 'order_id', 'customer_id')
    )
    op.create_table('coupon_product',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('coupon_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('id', 'coupon_id', 'product_id')
    )
    op.create_table('currency',
    sa.Column('currency_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=3), nullable=False),
    sa.Column('symbol_left', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('symbol_right', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('decimal_place', mysql.CHAR(length=1), nullable=False),
    sa.Column('value', mysql.DOUBLE(precision=15, scale=8, asdecimal=True), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('date_modified', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('currency_id')
    )
    op.create_table('custom_field',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('value', mysql.TEXT(), nullable=False),
    sa.Column('validation', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('location', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('sort_order', mysql.INTEGER(display_width=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_field_customer_group',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('customer_group_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('required', mysql.TINYINT(display_width=1), nullable=False),
    sa.PrimaryKeyConstraint('id', 'customer_group_id')
    )
    op.create_table('custom_field_description',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('language_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id', 'language_id')
    )
    op.create_table('custom_field_value',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('custom_field_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('sort_order', mysql.INTEGER(display_width=3), nullable=False),
    sa.PrimaryKeyConstraint('id', 'custom_field_id')
    )
    op.create_table('custom_field_value_description',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('language_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('custom_field_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id', 'language_id', 'custom_field_id')
    )
    op.create_table('customer',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('customer_group_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('store_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('language_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('firstname', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('lastname', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=96), nullable=False),
    sa.Column('telephone', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('fax', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('salt', mysql.VARCHAR(length=9), nullable=False),
    sa.Column('cart', mysql.TEXT(), nullable=True),
    sa.Column('wishlist', mysql.TEXT(), nullable=True),
    sa.Column('newsletter', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('address_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('custom_field', mysql.TEXT(), nullable=False),
    sa.Column('ip', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('safe', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('token', mysql.TEXT(), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'customer_group_id', 'store_id', 'language_id', 'address_id')
    )
    op.create_table('customer_activity',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('customer_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('key', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('data', mysql.TEXT(), nullable=False),
    sa.Column('ip', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'customer_id')
    )
    op.create_table('customer_affiliate',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('company', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('website', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('tracking', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('commission', mysql.DECIMAL(precision=4, scale=2), nullable=False),
    sa.Column('tax', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('payment', mysql.VARCHAR(length=6), nullable=False),
    sa.Column('cheque', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('paypal', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('bank_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('bank_branch_number', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('bank_swift_code', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('bank_account_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('bank_account_number', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('custom_field', mysql.TEXT(), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_approval',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('customer_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=9), nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'customer_id')
    )
    op.create_table('customer_group',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('approval', mysql.INTEGER(display_width=1), nullable=False),
    sa.Column('sort_order', mysql.INTEGER(display_width=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_group_description',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('language_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'language_id')
    )
    op.create_table('customer_history',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('customer_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('comment', mysql.TEXT(), nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'customer_id')
    )
    op.create_table('customer_ip',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('customer_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('ip', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'customer_id')
    )
    op.create_table('customer_login',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=96), nullable=False),
    sa.Column('ip', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('total', mysql.INTEGER(display_width=4), nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=False),
    sa.Column('date_modified', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_online',
    sa.Column('ip', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('url', mysql.TEXT(), nullable=False),
    sa.Column('referer', mysql.TEXT(), nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_reward',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('customer_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('order_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('poINTEGERs', mysql.INTEGER(display_width=8), nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'customer_id', 'order_id')
    )
    op.create_table('customer_search',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('store_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('language_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('customer_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('keyword', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('category_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('sub_category', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('description', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('products', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('ip', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'store_id', 'language_id', 'customer_id')
    )
    op.create_table('customer_transaction',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('customer_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('order_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('amount', mysql.DECIMAL(precision=15, scale=4), nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'customer_id', 'order_id')
    )
    op.create_table('customer_wishlist',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'product_id')
    )
    op.create_table('download',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('filename', mysql.VARCHAR(length=160), nullable=False),
    sa.Column('mask', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('download_description',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('language_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', 'language_id')
    )
    op.create_table('event',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('trigger', mysql.TEXT(), nullable=False),
    sa.Column('action', mysql.TEXT(), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('sort_order', mysql.INTEGER(display_width=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extension',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extension_install',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('extension_download_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('filename', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'extension_download_id')
    )
    op.create_table('extension_path',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('extension_install_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('path', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'extension_install_id')
    )
    op.create_table('filter',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('filter_group_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('sort_order', mysql.INTEGER(display_width=3), nullable=False),
    sa.PrimaryKeyConstraint('id', 'filter_group_id')
    )
    op.create_table('filter_description',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('language_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('filter_group_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', 'language_id', 'filter_group_id')
    )
    op.create_table('filter_group',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('sort_order', mysql.INTEGER(display_width=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filter_group_description',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('language_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', 'language_id')
    )
    op.create_table('geo_zone',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=False),
    sa.Column('date_modified', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('information',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('bottom', mysql.INTEGER(display_width=1), nullable=False),
    sa.Column('sort_order', mysql.INTEGER(display_width=3), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('information_description',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('language_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('description_medium', mysql.TEXT(), nullable=False),
    sa.Column('meta_title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('meta_description', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('meta_keyword', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', 'language_id')
    )
    op.create_table('information_to_layout',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('store_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('layout_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('id', 'store_id', 'layout_id')
    )
    op.create_table('information_to_store',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('store_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('id', 'store_id')
    )
    op.create_table('language',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=5), nullable=False),
    sa.Column('locale', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('image', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('directory', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('sort_order', mysql.INTEGER(display_width=3), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layout',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layout_module',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('layout_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('position', mysql.VARCHAR(length=14), nullable=False),
    sa.Column('sort_order', mysql.INTEGER(display_width=3), nullable=False),
    sa.PrimaryKeyConstraint('id', 'layout_id')
    )
    op.create_table('layout_route',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('layout_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('store_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('route', mysql.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', 'layout_id', 'store_id')
    )
    op.create_table('length_class',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('value', mysql.DECIMAL(precision=15, scale=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('length_class_description',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('language_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('unit', mysql.VARCHAR(length=4), nullable=False),
    sa.PrimaryKeyConstraint('id', 'language_id')
    )
    op.create_table('location',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('address', mysql.TEXT(), nullable=False),
    sa.Column('telephone', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('fax', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('geocode', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('image', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('open', mysql.TEXT(), nullable=False),
    sa.Column('comment', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lts_assigned_category',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('vendor_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('category_id', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'vendor_id')
    )
    op.create_table('lts_attribute',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('attribute_group_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('vendor_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('id', 'attribute_group_id', 'vendor_id')
    )
    op.create_table('lts_attribute_group',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('vendor_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('id', 'vendor_id')
    )
    op.create_table('lts_attribute_mapping',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('attribute', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('category_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('id', 'category_id')
    )
    op.create_table('lts_cart',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('cart_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('vendor_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('api_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('customer_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('session_id', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('quantity', mysql.INTEGER(display_width=5), nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'cart_id', 'vendor_id', 'api_id', 'customer_id', 'product_id')
    )
    op.create_table('lts_category',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('category_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('vendor_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('assigned', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('status', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('approved', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('id', 'category_id', 'vendor_id')
    )
    op.create_table('lts_commission',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('vendor_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('order_product_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('order_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('amount', mysql.DECIMAL(precision=15, scale=4), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=4), nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=False),
    sa.Column('date_modified', mysql.DATETIME(), nullable=False),
    sa.Column('default', mysql.INTEGER(display_width=12), nullable=False),
    sa.PrimaryKeyConstraint('id', 'vendor_id', 'order_product_id', 'product_id', 'order_id')
    )
    op.create_table('lts_coupon',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('coupon_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('vendor_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', 'coupon_id', 'vendor_id')
    )
    op.create_table('lts_download',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('vendor_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('id', 'vendor_id')
    )
    op.create_table('lts_filter_group',
    sa.Column('filter_group_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('vendor_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('filter_group_id')
    )
    op.create_table('lts_mail',
    sa.Column('id', mysql.INTEGER(display_width=10), nullable=False),
    sa.Column('too_id', mysql.INTEGER(display_width=2), nullable=False),
    sa.Column('subject', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('status', mysql.INTEGER(display_width=1), nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=False),
    sa.Column('date_modified', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lts_manufacturer',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('vendor_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('id', 'vendor_id')
    )
    op.create_table('lts_option',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('vendor_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('id', 'vendor_id')
    )
    op.create_table('lts_option_mapping',
    sa.Column('option_mapping_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('category_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('option', mysql.VARCHAR(length=260), nullable=False),
    sa.PrimaryKeyConstraint('option_mapping_id', 'category_id')
    )
    op.create_table('lts_order_history',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('order_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('vendor_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('order_status_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('notify', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('comment', mysql.TEXT(), nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'order_id', 'vendor_id', 'order_status_id')
    )
    op.create_table('lts_order_product',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('order_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('order_product_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('vendor_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('customer_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('order_status_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('quantity', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('total', mysql.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('tax', mysql.DECIMAL(precision=15, scale=4), nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=False),
    sa.Column('date_modified', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'order_id', 'order_product_id', 'vendor_id', 'product_id', 'customer_id', 'order_status_id')
    )
    op.create_table('lts_payment',
    sa.Column('id', mysql.INTEGER(display_width=13), nullable=False),
    sa.Column('paypal', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('account_holder', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('bankname', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('accountno', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('ifsc', mysql.VARCHAR(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lts_pincode',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('country_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('zone_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('status', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lts_pincode_status',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('pincode_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('pincode', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('status', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('id', 'pincode_id')
    )
    op.create_table('lts_plan',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('vendor_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('subscription_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('default', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('subscription_fee', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('subscription_commission', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('validity', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=False),
    sa.Column('date_expire', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'vendor_id', 'subscription_id', 'product_id')
    )
    op.create_table('lts_product',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('vendor_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('price', mysql.FLOAT(), nullable=False),
    sa.Column('quantity', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('status', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('approved', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('exist', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('id', 'product_id', 'vendor_id')
    )
    op.create_table('lts_product_exist',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('vendor_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('price', mysql.FLOAT(), nullable=False),
    sa.Column('quantity', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('status', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=True),
    sa.Column('date_modified', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'product_id', 'vendor_id')
    )
    op.create_table('lts_product_to_pincode',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('pincode_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('id', 'pincode_id')
    )
    op.create_table('lts_review',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('review_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('vendor_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('id', 'review_id', 'product_id', 'vendor_id')
    )
    op.create_table('lts_subscription',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('subscription_fee', mysql.DECIMAL(precision=10, scale=0), nullable=False),
    sa.Column('status', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('subscription_commission', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('default', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=False),
    sa.Column('date_modified', mysql.DATETIME(), nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('plan_type', mysql.INTEGER(display_width=2), nullable=False),
    sa.PrimaryKeyConstraint('id', 'product_id')
    )
    op.create_table('lts_subscription_description',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('language_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'language_id')
    )
    op.create_table('lts_too',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lts_vendor',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('customer_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('commission_rate', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('meta_title', mysql.VARCHAR(length=65), nullable=False),
    sa.Column('meta_description', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('meta_keyword', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('store_owner', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('store_name', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('address', mysql.TEXT(), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=35), nullable=False),
    sa.Column('telephone', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('fax', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('country_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('zone_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('city', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('logo', mysql.TEXT(), nullable=False),
    sa.Column('banner', mysql.TEXT(), nullable=False),
    sa.Column('profile_image', mysql.TEXT(), nullable=True),
    sa.Column('facebook', mysql.TEXT(), nullable=False),
    sa.Column('instagram', mysql.TEXT(), nullable=False),
    sa.Column('youtube', mysql.TEXT(), nullable=False),
    sa.Column('twitter', mysql.TEXT(), nullable=False),
    sa.Column('pINTEGERerest', mysql.TEXT(), nullable=False),
    sa.Column('status', mysql.INTEGER(display_width=2), nullable=False),
    sa.Column('approved', mysql.INTEGER(display_width=2), nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'customer_id', 'country_id', 'zone_id')
    )
    op.create_table('lts_withdrawal',
    sa.Column('id', mysql.INTEGER(display_width=255), nullable=False),
    sa.Column('vendor_id', mysql.INTEGER(display_width=155), nullable=False),
    sa.Column('vendor_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('amount', mysql.DECIMAL(precision=15, scale=3), nullable=False),
    sa.Column('payment_processed', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('withdrawal_initiate_date', mysql.DATETIME(), nullable=False),
    sa.Column('bank_name', mysql.VARCHAR(length=155), nullable=False),
    sa.Column('payment_mode', mysql.VARCHAR(length=155), nullable=False),
    sa.Column('transection_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('vendor_bank_account_no', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('payment_initiate_date', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manufacturer',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('image', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('sort_order', mysql.INTEGER(display_width=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manufacturer_to_store',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('store_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('id', 'store_id')
    )
    op.create_table('marketing',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('clicks', mysql.INTEGER(display_width=5), nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modification',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('extension_install_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('author', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('version', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('link', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('xml_medium', mysql.TEXT(), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('date_add', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'extension_install_id')
    )
    op.create_table('module',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('setting', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('option',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('sort_order', mysql.INTEGER(display_width=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('option_description',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('language_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id', 'language_id')
    )
    op.create_table('option_value',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('option_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('image', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('sort_order', mysql.INTEGER(display_width=3), nullable=False),
    sa.PrimaryKeyConstraint('id', 'option_id')
    )
    op.create_table('option_value_description',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('language_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('option_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id', 'language_id', 'option_id')
    )
    op.create_table('order',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('invoice_no', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('invoice_prefix', mysql.VARCHAR(length=26), nullable=False),
    sa.Column('store_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('store_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('store_url', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('customer_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('customer_group_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('firstname', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('lastname', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=96), nullable=False),
    sa.Column('telephone', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('fax', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('custom_field', mysql.TEXT(), nullable=False),
    sa.Column('payment_firstname', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('payment_lastname', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('payment_company', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('payment_address_1', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('payment_address_2', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('payment_city', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('payment_postcode', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('payment_country', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('payment_country_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('payment_zone', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('payment_zone_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('payment_address_format', mysql.TEXT(), nullable=False),
    sa.Column('payment_custom_field', mysql.TEXT(), nullable=False),
    sa.Column('payment_method', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('payment_code', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('shipping_firstname', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('shipping_lastname', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('shipping_company', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('shipping_address_1', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('shipping_address_2', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('shipping_city', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('shipping_postcode', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('shipping_country', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('shipping_country_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('shipping_zone', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('shipping_zone_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('shipping_address_format', mysql.TEXT(), nullable=False),
    sa.Column('shipping_custom_field', mysql.TEXT(), nullable=False),
    sa.Column('shipping_method', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('shipping_code', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('comment', mysql.TEXT(), nullable=False),
    sa.Column('total', mysql.DECIMAL(precision=15, scale=4), nullable=False),
    sa.Column('order_status_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('affiliate_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('commission', mysql.DECIMAL(precision=15, scale=4), nullable=False),
    sa.Column('marketing_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('tracking', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('language_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('currency_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('currency_code', mysql.VARCHAR(length=3), nullable=False),
    sa.Column('currency_value', mysql.DECIMAL(precision=15, scale=8), nullable=False),
    sa.Column('ip', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('forwarded_ip', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('user_agent', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('accept_language', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=False),
    sa.Column('date_modified', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'store_id', 'customer_id', 'customer_group_id', 'payment_country_id', 'payment_zone_id', 'shipping_country_id', 'shipping_zone_id', 'order_status_id', 'affiliate_id', 'marketing_id', 'language_id', 'currency_id')
    )
    op.create_table('order_history',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('order_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('order_status_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('notify', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('comment', mysql.TEXT(), nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'order_id', 'order_status_id')
    )
    op.create_table('order_option',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('order_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('order_product_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('product_option_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('product_option_value_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('value', mysql.TEXT(), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', 'order_id', 'order_product_id', 'product_option_id', 'product_option_value_id')
    )
    op.create_table('order_product',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('order_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('model', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('quantity', mysql.INTEGER(display_width=4), nullable=False),
    sa.Column('price', mysql.DECIMAL(precision=15, scale=4), nullable=False),
    sa.Column('total', mysql.DECIMAL(precision=15, scale=4), nullable=False),
    sa.Column('tax', mysql.DECIMAL(precision=15, scale=4), nullable=False),
    sa.Column('reward', mysql.INTEGER(display_width=8), nullable=False),
    sa.PrimaryKeyConstraint('id', 'order_id', 'product_id')
    )
    op.create_table('order_recurring',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('order_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('reference', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('product_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('product_quantity', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('recurring_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('recurring_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('recurring_description', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('recurring_frequency', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('recurring_cycle_small', mysql.INTEGER(display_width=6), nullable=False),
    sa.Column('recurring_duration_small', mysql.INTEGER(display_width=6), nullable=False),
    sa.Column('recurring_price', mysql.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('trial', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('trial_frequency', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('trial_cycle_small', mysql.INTEGER(display_width=6), nullable=False),
    sa.Column('trial_duration_small', mysql.INTEGER(display_width=6), nullable=False),
    sa.Column('trial_price', mysql.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=4), nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'order_id', 'product_id', 'recurring_id')
    )
    op.create_table('order_recurring_transaction',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('order_recurring_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('reference', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('amount', mysql.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'order_recurring_id')
    )
    op.create_table('order_shipment',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('order_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=False),
    sa.Column('shipping_courier_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('tracking_number', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', 'order_id')
    )
    op.create_table('order_status',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('language_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', 'language_id')
    )
    op.create_table('order_total',
    sa.Column('id', mysql.INTEGER(display_width=10), nullable=False),
    sa.Column('order_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('value', mysql.DECIMAL(precision=15, scale=4), nullable=False),
    sa.Column('sort_order', mysql.INTEGER(display_width=3), nullable=False),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('order_voucher',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('order_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('voucher_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('from_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('from_email', mysql.VARCHAR(length=96), nullable=False),
    sa.Column('to_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('to_email', mysql.VARCHAR(length=96), nullable=False),
    sa.Column('voucher_theme_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('amount', mysql.DECIMAL(precision=15, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id', 'order_id', 'voucher_id', 'voucher_theme_id')
    )
    op.create_table('product_advertise_google',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('store_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('has_issues', mysql.TINYINT(display_width=1), nullable=True),
    sa.Column('destination_status', mysql.ENUM('pending', 'approved', 'disapproved'), nullable=False),
    sa.Column('impressions', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('clicks', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('conversions', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('cost', mysql.DECIMAL(precision=15, scale=4), nullable=False),
    sa.Column('conversion_value', mysql.DECIMAL(precision=15, scale=4), nullable=False),
    sa.Column('google_product_category', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('condition', mysql.ENUM('new', 'refurbished', 'used'), nullable=True),
    sa.Column('adult', mysql.TINYINT(display_width=1), nullable=True),
    sa.Column('multipack', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('is_bundle', mysql.TINYINT(display_width=1), nullable=True),
    sa.Column('age_group', mysql.ENUM('newborn', 'infant', 'toddler', 'kids', 'adult'), nullable=False),
    sa.Column('color', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('gender', mysql.ENUM('male', 'female', 'unisex'), nullable=True),
    sa.Column('size_type', mysql.ENUM('regular', 'petite', 'plus', 'big and tall', 'maternity'), nullable=True),
    sa.Column('size_system', mysql.ENUM('AU', 'BR', 'CN', 'DE', 'EU', 'FR', 'IT', 'JP', 'MEX', 'UK', 'US'), nullable=True),
    sa.Column('size', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('is_modified', mysql.TINYINT(display_width=1), nullable=False),
    sa.PrimaryKeyConstraint('id', 'store_id')
    )
    op.create_table('product_advertise_google_status',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('store_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('product_variation_id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('destination_statuses', mysql.TEXT(), nullable=False),
    sa.Column('data_quality_issues', mysql.TEXT(), nullable=False),
    sa.Column('item_level_issues', mysql.TEXT(), nullable=False),
    sa.Column('google_expiration_date', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('id', 'store_id')
    )
    op.create_table('product_advertise_google_target',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('store_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('advertise_google_target_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('id', 'store_id')
    )
    op.create_table('product_attribute',
    sa.Column('product_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('attribute_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('language_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('text', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('product_id', 'attribute_id', 'language_id')
    )
    op.create_table('product_description',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('language_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('tag', mysql.TEXT(), nullable=False),
    sa.Column('meta_title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('meta_description', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('meta_keyword', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', 'language_id')
    )
    op.create_table('product_discount',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('customer_group_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('quantity', mysql.INTEGER(display_width=4), nullable=False),
    sa.Column('priority', mysql.INTEGER(display_width=5), nullable=False),
    sa.Column('price', mysql.DECIMAL(precision=15, scale=4), nullable=False),
    sa.Column('date_start', mysql.DATETIME(), nullable=False),
    sa.Column('date_end', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'product_id', 'customer_group_id')
    )
    op.create_table('product_filter',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('filter_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('id', 'filter_id')
    )
    op.create_table('product_image',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('image', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('sort_order', mysql.INTEGER(display_width=3), nullable=False),
    sa.PrimaryKeyConstraint('id', 'product_id')
    )
    op.create_table('product_option',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('option_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('value', mysql.TEXT(), nullable=False),
    sa.Column('required', mysql.TINYINT(display_width=1), nullable=False),
    sa.PrimaryKeyConstraint('id', 'product_id', 'option_id')
    )
    op.create_table('product_option_value',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('product_option_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('option_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('option_value_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('quantity', mysql.INTEGER(display_width=3), nullable=False),
    sa.Column('subtract', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('price', mysql.DECIMAL(precision=15, scale=4), nullable=False),
    sa.Column('price_prefix', mysql.VARCHAR(length=1), nullable=False),
    sa.Column('poINTEGERs', mysql.INTEGER(display_width=8), nullable=False),
    sa.Column('poINTEGERs_prefix', mysql.VARCHAR(length=1), nullable=False),
    sa.Column('weight', mysql.DECIMAL(precision=15, scale=8), nullable=False),
    sa.Column('weight_prefix', mysql.VARCHAR(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id', 'product_option_id', 'product_id', 'option_id', 'option_value_id')
    )
    op.create_table('product_recurring',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('recurring_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('customer_group_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('id', 'recurring_id', 'customer_group_id')
    )
    op.create_table('product_related',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('related_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('id', 'related_id')
    )
    op.create_table('product_reward',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('customer_group_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('poINTEGERs', mysql.INTEGER(display_width=8), nullable=False),
    sa.PrimaryKeyConstraint('id', 'product_id', 'customer_group_id')
    )
    op.create_table('product_special',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('customer_group_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('priority', mysql.INTEGER(display_width=5), nullable=False),
    sa.Column('price', mysql.DECIMAL(precision=15, scale=4), nullable=False),
    sa.Column('date_start', mysql.DATETIME(), nullable=False),
    sa.Column('date_end', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'product_id', 'customer_group_id')
    )
    op.create_table('product_to_category',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('category_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('id', 'category_id')
    )
    op.create_table('product_to_download',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('download_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('id', 'download_id')
    )
    op.create_table('product_to_layout',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('store_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('layout_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('id', 'store_id', 'layout_id')
    )
    op.create_table('product_to_store',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('store_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('id', 'store_id')
    )
    op.create_table('py_return',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('order_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('customer_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('firstname', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('lastname', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=96), nullable=False),
    sa.Column('telephone', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('product', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('model', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('quantity', mysql.INTEGER(display_width=4), nullable=False),
    sa.Column('opened', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('return_reason_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('return_action_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('return_status_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('comment', mysql.TEXT(), nullable=True),
    sa.Column('date_ordered', mysql.DATETIME(), nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=False),
    sa.Column('date_modified', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'order_id', 'product_id', 'customer_id', 'return_reason_id', 'return_action_id', 'return_status_id')
    )
    op.create_table('recurring',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('frequency', mysql.ENUM('day', 'week', 'semi_month', 'month', 'year'), nullable=False),
    sa.Column('duration', mysql.INTEGER(display_width=10), nullable=False),
    sa.Column('cycle', mysql.INTEGER(display_width=10), nullable=False),
    sa.Column('trial_status', mysql.TINYINT(display_width=4), nullable=False),
    sa.Column('trial_price', mysql.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('trial_frequency', mysql.ENUM('day', 'week', 'semi_month', 'month', 'year'), nullable=False),
    sa.Column('trial_duration', mysql.INTEGER(display_width=10), nullable=False),
    sa.Column('trial_cycle', mysql.INTEGER(display_width=10), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=4), nullable=False),
    sa.Column('sort_order', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recurring_description',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('language_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', 'language_id')
    )
    op.create_table('return_action',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('language_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', 'language_id')
    )
    op.create_table('return_history',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('return_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('return_status_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('notify', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('comment', mysql.TEXT(), nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'return_id', 'return_status_id')
    )
    op.create_table('return_reason',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('language_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id', 'language_id')
    )
    op.create_table('return_status',
    sa.Column('return_status_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('language_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('return_status_id', 'language_id')
    )
    op.create_table('review',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('customer_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('author', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('text', mysql.TEXT(), nullable=False),
    sa.Column('rating', mysql.INTEGER(display_width=1), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=False),
    sa.Column('date_modified', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'product_id', 'customer_id')
    )
    op.create_table('seo_url',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('store_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('language_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('query', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('keyword', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', 'store_id', 'language_id')
    )
    op.create_table('session',
    sa.Column('id', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('data', mysql.TEXT(), nullable=False),
    sa.Column('expire', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setting',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('store_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('key', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('value', mysql.TEXT(), nullable=False),
    sa.Column('serialized', mysql.TINYINT(display_width=1), nullable=False),
    sa.PrimaryKeyConstraint('id', 'store_id')
    )
    op.create_table('shipping_courier',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('shipping_courier_code', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('shipping_courier_name', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statistics',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('value', mysql.DECIMAL(precision=15, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_status',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('language_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', 'language_id')
    )
    op.create_table('store',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('url', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('ssl', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_class',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=False),
    sa.Column('date_modified', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_rate',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('geo_zone_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('rate', mysql.DECIMAL(precision=15, scale=4), nullable=False),
    sa.Column('type', mysql.CHAR(length=1), nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=False),
    sa.Column('date_modified', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'geo_zone_id')
    )
    op.create_table('zone_to_geo_zone',
    sa.Column('zone_to_geo_zone_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('country_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('zone_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('geo_zone_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_added', mysql.DATETIME(), nullable=False),
    sa.Column('date_modified', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('zone_to_geo_zone_id', 'country_id', 'zone_id', 'geo_zone_id')
    )
    op.add_column('product', sa.Column('poINTEGERs', mysql.INTEGER(display_width=8), nullable=False))
    op.alter_column('product', 'date_available',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('product', 'points')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('points', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.alter_column('product', 'date_available',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_column('product', 'poINTEGERs')
    op.drop_table('zone_to_geo_zone')
    op.drop_table('tax_rate')
    op.drop_table('tax_class')
    op.drop_table('store')
    op.drop_table('stock_status')
    op.drop_table('statistics')
    op.drop_table('shipping_courier')
    op.drop_table('setting')
    op.drop_table('session')
    op.drop_table('seo_url')
    op.drop_table('review')
    op.drop_table('return_status')
    op.drop_table('return_reason')
    op.drop_table('return_history')
    op.drop_table('return_action')
    op.drop_table('recurring_description')
    op.drop_table('recurring')
    op.drop_table('py_return')
    op.drop_table('product_to_store')
    op.drop_table('product_to_layout')
    op.drop_table('product_to_download')
    op.drop_table('product_to_category')
    op.drop_table('product_special')
    op.drop_table('product_reward')
    op.drop_table('product_related')
    op.drop_table('product_recurring')
    op.drop_table('product_option_value')
    op.drop_table('product_option')
    op.drop_table('product_image')
    op.drop_table('product_filter')
    op.drop_table('product_discount')
    op.drop_table('product_description')
    op.drop_table('product_attribute')
    op.drop_table('product_advertise_google_target')
    op.drop_table('product_advertise_google_status')
    op.drop_table('product_advertise_google')
    op.drop_table('order_voucher')
    op.drop_table('order_total')
    op.drop_table('order_status')
    op.drop_table('order_shipment')
    op.drop_table('order_recurring_transaction')
    op.drop_table('order_recurring')
    op.drop_table('order_product')
    op.drop_table('order_option')
    op.drop_table('order_history')
    op.drop_table('order')
    op.drop_table('option_value_description')
    op.drop_table('option_value')
    op.drop_table('option_description')
    op.drop_table('option')
    op.drop_table('module')
    op.drop_table('modification')
    op.drop_table('marketing')
    op.drop_table('manufacturer_to_store')
    op.drop_table('manufacturer')
    op.drop_table('lts_withdrawal')
    op.drop_table('lts_vendor')
    op.drop_table('lts_too')
    op.drop_table('lts_subscription_description')
    op.drop_table('lts_subscription')
    op.drop_table('lts_review')
    op.drop_table('lts_product_to_pincode')
    op.drop_table('lts_product_exist')
    op.drop_table('lts_product')
    op.drop_table('lts_plan')
    op.drop_table('lts_pincode_status')
    op.drop_table('lts_pincode')
    op.drop_table('lts_payment')
    op.drop_table('lts_order_product')
    op.drop_table('lts_order_history')
    op.drop_table('lts_option_mapping')
    op.drop_table('lts_option')
    op.drop_table('lts_manufacturer')
    op.drop_table('lts_mail')
    op.drop_table('lts_filter_group')
    op.drop_table('lts_download')
    op.drop_table('lts_coupon')
    op.drop_table('lts_commission')
    op.drop_table('lts_category')
    op.drop_table('lts_cart')
    op.drop_table('lts_attribute_mapping')
    op.drop_table('lts_attribute_group')
    op.drop_table('lts_attribute')
    op.drop_table('lts_assigned_category')
    op.drop_table('location')
    op.drop_table('length_class_description')
    op.drop_table('length_class')
    op.drop_table('layout_route')
    op.drop_table('layout_module')
    op.drop_table('layout')
    op.drop_table('language')
    op.drop_table('information_to_store')
    op.drop_table('information_to_layout')
    op.drop_table('information_description')
    op.drop_table('information')
    op.drop_table('geo_zone')
    op.drop_table('filter_group_description')
    op.drop_table('filter_group')
    op.drop_table('filter_description')
    op.drop_table('filter')
    op.drop_table('extension_path')
    op.drop_table('extension_install')
    op.drop_table('extension')
    op.drop_table('event')
    op.drop_table('download_description')
    op.drop_table('download')
    op.drop_table('customer_wishlist')
    op.drop_table('customer_transaction')
    op.drop_table('customer_search')
    op.drop_table('customer_reward')
    op.drop_table('customer_online')
    op.drop_table('customer_login')
    op.drop_table('customer_ip')
    op.drop_table('customer_history')
    op.drop_table('customer_group_description')
    op.drop_table('customer_group')
    op.drop_table('customer_approval')
    op.drop_table('customer_affiliate')
    op.drop_table('customer_activity')
    op.drop_table('customer')
    op.drop_table('custom_field_value_description')
    op.drop_table('custom_field_value')
    op.drop_table('custom_field_description')
    op.drop_table('custom_field_customer_group')
    op.drop_table('custom_field')
    op.drop_table('currency')
    op.drop_table('coupon_product')
    op.drop_table('coupon_history')
    op.drop_table('coupon_category')
    op.drop_table('coupon')
    op.drop_table('country')
    op.drop_table('category_to_store')
    op.drop_table('category_to_layout')
    op.drop_table('category_to_google_product_category')
    op.drop_table('category_path')
    op.drop_table('category_filter')
    op.drop_table('category_description')
    op.drop_table('category')
    op.drop_table('banner_image')
    op.drop_table('banner')
    op.drop_table('attribute_group_description')
    op.drop_table('attribute_group')
    op.drop_table('attribute_description')
    op.drop_table('attribute')
    op.drop_table('api_session')
    op.drop_table('api_ip')
    op.drop_table('api')
    op.drop_table('advertise_google_target')
    op.drop_table('address')
    # ### end Alembic commands ###
