"""Merged the two user tables

Revision ID: 5754e8177d9d
Revises: 59c0113a8e1c
Create Date: 2023-02-17 22:25:31.244863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5754e8177d9d'
down_revision = '59c0113a8e1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'users', ['name'], unique=False)
    # ### end Alembic commands ###
