"""Change firstName and lastName to firstname and lastname in sellers table

Revision ID: 742f3a0f0697
Revises: 46e5b879188c
Create Date: 2023-03-09 21:41:15.515409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '742f3a0f0697'
down_revision = '46e5b879188c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('firstname', sa.String(length=125), nullable=False))
    op.add_column('sellers', sa.Column('lastname', sa.String(length=125), nullable=False))
    op.drop_column('sellers', 'lastName')
    op.drop_column('sellers', 'firstName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('firstName', sa.VARCHAR(length=125), nullable=False))
    op.add_column('sellers', sa.Column('lastName', sa.VARCHAR(length=125), nullable=False))
    op.drop_column('sellers', 'lastname')
    op.drop_column('sellers', 'firstname')
    # ### end Alembic commands ###
