"""Added manufacturer table

Revision ID: a65e1845bee4
Revises: 769a6432b3d1
Create Date: 2023-03-31 06:19:45.179459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a65e1845bee4'
down_revision = '769a6432b3d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manufacturer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_group_id', sa.INTEGER(), nullable=False),
    sa.Column('store_id', sa.INTEGER(), nullable=False),
    sa.Column('language_id', sa.INTEGER(), nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=32), nullable=False),
    sa.Column('lastname', sa.VARCHAR(length=32), nullable=False),
    sa.Column('email', sa.VARCHAR(length=96), nullable=False),
    sa.Column('telephone', sa.VARCHAR(length=32), nullable=False),
    sa.Column('fax', sa.VARCHAR(length=32), nullable=False),
    sa.Column('password', sa.VARCHAR(length=40), nullable=False),
    sa.Column('salt', sa.VARCHAR(length=9), nullable=False),
    sa.Column('cart', sa.TEXT(), nullable=True),
    sa.Column('wishlist', sa.TEXT(), nullable=True),
    sa.Column('newsletter', sa.INTEGER(), nullable=False),
    sa.Column('address_id', sa.INTEGER(), nullable=False),
    sa.Column('custom_field', sa.TEXT(), nullable=False),
    sa.Column('ip', sa.VARCHAR(length=40), nullable=False),
    sa.Column('status', sa.INTEGER(), nullable=False),
    sa.Column('safe', sa.INTEGER(), nullable=False),
    sa.Column('token', sa.TEXT(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=40), nullable=False),
    sa.Column('date_added', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('manufacturer')
    # ### end Alembic commands ###
