"""added seller_id column to cart table

Revision ID: ad29f73bd6c1
Revises: 4e916f3db7a7
Create Date: 2023-02-20 21:10:53.332306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad29f73bd6c1'
down_revision = '4e916f3db7a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('seller_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'cart', 'sellers', ['seller_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_column('cart', 'seller_id')
    # ### end Alembic commands ###
