"""products.price changed to products.product_price

Revision ID: d3b2b2b08333
Revises: ad29f73bd6c1
Create Date: 2023-02-20 22:02:35.821750

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd3b2b2b08333'
down_revision = 'ad29f73bd6c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_price', sa.Float(), nullable=False))
    op.drop_column('products', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price', mysql.FLOAT(), nullable=False))
    op.drop_column('products', 'product_price')
    # ### end Alembic commands ###
