"""Added seller_id to Product for relationship purposes

Revision ID: 2b3ec8b5e26c
Revises: de7c5435f614
Create Date: 2023-02-25 17:48:47.412002

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2b3ec8b5e26c'
down_revision = 'de7c5435f614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('seller_id', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('model', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('sku', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('upc', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('ean', mysql.VARCHAR(length=14), nullable=False),
    sa.Column('jan', mysql.VARCHAR(length=13), nullable=False),
    sa.Column('isbn', mysql.VARCHAR(length=17), nullable=False),
    sa.Column('mpn', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('location', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('quantity', mysql.INTEGER(display_width=4), nullable=False),
    sa.Column('stock_status_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('image', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('manufacturer_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('shipping', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('price', mysql.DECIMAL(precision=15, scale=4), nullable=False),
    sa.Column('points', mysql.INTEGER(display_width=8), nullable=False),
    sa.Column('tax_class_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_available', sa.DATE(), nullable=False),
    sa.Column('weight', mysql.DECIMAL(precision=15, scale=8), nullable=False),
    sa.Column('weight_class_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('length', mysql.DECIMAL(precision=15, scale=8), nullable=False),
    sa.Column('width', mysql.DECIMAL(precision=15, scale=8), nullable=False),
    sa.Column('height', mysql.DECIMAL(precision=15, scale=8), nullable=False),
    sa.Column('length_class_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('subtract', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('minimum', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('sort_order', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('viewed', mysql.INTEGER(display_width=5), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('date_modified', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('cart', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)
    op.alter_column('order_option', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)
    op.alter_column('order_product', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.add_column('sellers', sa.Column('product_id', mysql.INTEGER(display_width=11), nullable=False))
    op.create_foreign_key(None, 'sellers', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sellers', type_='foreignkey')
    op.drop_column('sellers', 'product_id')
    op.alter_column('order_product', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('order_option', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.alter_column('cart', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.drop_table('products')
    # ### end Alembic commands ###
