"""Added prdouct_id back to product_description

Revision ID: 3df960e934b3
Revises: a7d63b2dafab
Create Date: 2023-03-01 07:32:02.766105

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3df960e934b3'
down_revision = 'd5ead5c518b8' # a7d63b2dafab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)
    op.alter_column('order_option', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)
    op.alter_column('order_product', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.add_column('product_description', sa.Column('product_id', mysql.INTEGER(display_width=11), nullable=False))
    op.drop_constraint('product_description_ibfk_1', 'product_description', type_='foreignkey')
    op.create_foreign_key(None, 'product_description', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_description', type_='foreignkey')
    op.create_foreign_key('product_description_ibfk_1', 'product_description', 'products', ['id'], ['id'])
    op.drop_column('product_description', 'product_id')
    op.alter_column('order_product', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('order_option', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.alter_column('cart', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
