"""Added OrderShipment and OrderRecurringTransaction Tables

Revision ID: 9b4d8e0bfd67
Revises: fa9332af67e1
Create Date: 2023-02-23 22:05:46.391711

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9b4d8e0bfd67'
down_revision = 'fa9332af67e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_recurring_transaction',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('order_recurring_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('reference', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('amount', mysql.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_shipment',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('order_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('shipping_courier_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('tracking_number', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('order_option', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)
    op.alter_column('order_product', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_product', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('order_option', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.drop_table('order_shipment')
    op.drop_table('order_recurring_transaction')
    # ### end Alembic commands ###
