"""Removed product_id from product_description and make id a foreign key pointing to products.id and added language table

Revision ID: d5ead5c518b8
Revises: f8018a0f82ba
Create Date: 2023-03-01 07:16:00.691398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5ead5c518b8'
down_revision = 'f8018a0f82ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language',
    sa.Column('id', mysql.INTEGER(), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=5), nullable=False),
    sa.Column('locale', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('image', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('directory', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('sort_order', mysql.INTEGER(), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('cart', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)
    op.alter_column('order_option', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)
    op.alter_column('order_product', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint('product_description_ibfk_1', 'product_description', type_='foreignkey')
    op.create_foreign_key(None, 'product_description', 'products', ['id'], ['id'])
    op.create_foreign_key(None, 'product_description', 'language', ['language_id'], ['id'])
    op.drop_column('product_description', 'product_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_description', sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'product_description', type_='foreignkey')
    op.drop_constraint(None, 'product_description', type_='foreignkey')
    op.create_foreign_key('product_description_ibfk_1', 'product_description', 'products', ['product_id'], ['id'])
    op.alter_column('order_product', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('order_option', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.alter_column('cart', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.drop_table('language')
    # ### end Alembic commands ###
