"""Added Cart, Customer and Category Tables

Revision ID: de7c5435f614
Revises: 9b4d8e0bfd67
Create Date: 2023-02-23 22:08:38.999859

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de7c5435f614'
down_revision = '9b4d8e0bfd67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('api_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('customer_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('session_id', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('recurring_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('option', mysql.TEXT(), nullable=False),
    sa.Column('quantity', mysql.INTEGER(display_width=5), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('image', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('parent_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('top', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('column', mysql.INTEGER(display_width=3), nullable=False),
    sa.Column('sort_order', mysql.INTEGER(display_width=3), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('date_modified', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_login',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=96), nullable=False),
    sa.Column('ip', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('total', mysql.INTEGER(display_width=4), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('date_modified', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('order_option', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)
    op.alter_column('order_product', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_product', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('order_option', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.drop_table('customer_login')
    op.drop_table('category')
    op.drop_table('cart')
    # ### end Alembic commands ###
