"""Added ProductDescription table

Revision ID: f44497826182
Revises: 2b3ec8b5e26c
Create Date: 2023-02-25 18:34:01.680654

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f44497826182'
down_revision = '2b3ec8b5e26c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_description',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('language_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.INTEGER(display_width=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('tag', mysql.TEXT(), nullable=False),
    sa.Column('meta_title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('meta_description', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('meta_keyword', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', 'language_id')
    )
    op.alter_column('cart', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)
    op.alter_column('order_option', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)
    op.alter_column('order_product', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_product', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('order_option', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.alter_column('cart', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.drop_table('product_description')
    # ### end Alembic commands ###
