"""Restarted

Revision ID: 7ca12740eeef
Revises: 
Create Date: 2023-03-01 08:28:39.028217

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import flask_authorize 

# revision identifiers, used by Alembic.
revision = '7ca12740eeef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('api_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('customer_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('session_id', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('recurring_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('option', mysql.TEXT(), nullable=False),
    sa.Column('quantity', mysql.INTEGER(display_width=5), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('image', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('parent_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('top', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('column', mysql.INTEGER(display_width=3), nullable=False),
    sa.Column('sort_order', mysql.INTEGER(display_width=3), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('date_modified', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_filter',
    sa.Column('category_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('filter_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('category_id', 'filter_id')
    )
    op.create_table('category_path',
    sa.Column('category_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('path_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('level', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('category_id', 'path_id')
    )
    op.create_table('category_to_google_product_category',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('google_product_category', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('store_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('category_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('id', 'store_id', 'category_id')
    )
    op.create_table('category_to_layout',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('store_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('layout_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('id', 'store_id')
    )
    op.create_table('category_to_store',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('store_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('id', 'store_id')
    )
    op.create_table('customer',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('customer_group_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('store_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('firstname', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('lastname', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=96), nullable=False),
    sa.Column('telephone', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('fax', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('salt', mysql.VARCHAR(length=9), nullable=False),
    sa.Column('cart', mysql.TEXT(), nullable=True),
    sa.Column('wishlist', mysql.TEXT(), nullable=True),
    sa.Column('newsletter', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('address_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('custom_field', mysql.TEXT(), nullable=False),
    sa.Column('ip', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('safe', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('token', mysql.TEXT(), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_activity',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('customer_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('key', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('data', mysql.TEXT(), nullable=False),
    sa.Column('ip', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_affiliate',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('company', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('website', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('tracking', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('commission', mysql.DECIMAL(precision=4, scale=2), nullable=False),
    sa.Column('tax', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('payment', mysql.VARCHAR(length=6), nullable=False),
    sa.Column('cheque', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('paypal', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('bank_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('bank_branch_number', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('bank_swift_code', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('bank_account_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('bank_account_number', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('custom_field', mysql.TEXT(), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_approval',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('customer_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=9), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_group',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('approval', mysql.INTEGER(display_width=1), nullable=False),
    sa.Column('sort_order', mysql.INTEGER(display_width=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_group_description',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('language_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_history',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('customer_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('comment', mysql.TEXT(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_ip',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('customer_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('ip', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_login',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=96), nullable=False),
    sa.Column('ip', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('total', mysql.INTEGER(display_width=4), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('date_modified', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_online',
    sa.Column('ip', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('customer_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('url', mysql.TEXT(), nullable=False),
    sa.Column('referer', mysql.TEXT(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ip')
    )
    op.create_table('customer_reward',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('customer_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('order_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('points', mysql.INTEGER(display_width=8), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_search',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('store_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('language_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('customer_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('keyword', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('category_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('sub_category', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('description', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('products', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('ip', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('customer_transaction',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('customer_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('order_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('amount', mysql.DECIMAL(precision=15, scale=4), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_wishlist',
    sa.Column('iid', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('iid', 'product_id')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('restrictions', flask_authorize.mixins.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('language',
    sa.Column('id', mysql.INTEGER(), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=5), nullable=False),
    sa.Column('locale', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('image', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('directory', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('sort_order', mysql.INTEGER(), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('invoice_no', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('invoice_prefix', mysql.VARCHAR(length=26), nullable=False),
    sa.Column('store_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('store_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('store_url', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('customer_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('customer_group_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('firstname', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('lastname', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=96), nullable=False),
    sa.Column('telephone', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('fax', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('custom_field', mysql.TEXT(), nullable=False),
    sa.Column('payment_firstname', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('payment_lastname', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('payment_company', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('payment_address_1', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('payment_address_2', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('payment_city', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('payment_postcode', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('payment_country', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('payment_country_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('payment_zone', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('payment_zone_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('payment_address_format', mysql.TEXT(), nullable=False),
    sa.Column('payment_custom_field', mysql.TEXT(), nullable=False),
    sa.Column('payment_method', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('payment_code', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('shipping_firstname', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('shipping_lastname', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('shipping_company', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('shipping_address_1', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('shipping_address_2', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('shipping_city', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('shipping_postcode', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('shipping_country', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('shipping_country_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('shipping_zone', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('shipping_zone_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('shipping_address_format', mysql.TEXT(), nullable=False),
    sa.Column('shipping_custom_field', mysql.TEXT(), nullable=False),
    sa.Column('shipping_method', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('shipping_code', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('comment', mysql.TEXT(), nullable=False),
    sa.Column('total', mysql.DECIMAL(precision=15, scale=4), nullable=False),
    sa.Column('order_status_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('affiliate_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('commission', mysql.DECIMAL(precision=15, scale=4), nullable=False),
    sa.Column('marketing_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('tracking', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('language_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('currency_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('currency_code', mysql.VARCHAR(length=3), nullable=False),
    sa.Column('currency_value', mysql.DECIMAL(precision=15, scale=8), nullable=False),
    sa.Column('ip', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('forwarded_ip', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('user_agent', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('accept_language', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_history',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('order_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('order_status_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('notify', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('comment', mysql.TEXT(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_option',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('order_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('order_product_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('product_option_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('product_option_value_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('value', mysql.TEXT(), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_product',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('order_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('model', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('quantity', mysql.INTEGER(display_width=4), nullable=False),
    sa.Column('price', mysql.DECIMAL(precision=15, scale=4), nullable=False),
    sa.Column('total', mysql.DECIMAL(precision=15, scale=4), nullable=False),
    sa.Column('tax', mysql.DECIMAL(precision=15, scale=4), nullable=False),
    sa.Column('reward', mysql.INTEGER(display_width=8), nullable=False),
    sa.PrimaryKeyConstraint('id', 'order_id')
    )
    op.create_table('order_recurring',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('order_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('reference', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('product_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('product_quantity', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('recurring_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('recurring_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('recurring_description', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('recurring_frequency', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('recurring_cycle', mysql.SMALLINT(display_width=6), nullable=False),
    sa.Column('recurring_duration', mysql.SMALLINT(display_width=6), nullable=False),
    sa.Column('recurring_price', mysql.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('trial', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('trial_frequency', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('trial_cycle', mysql.SMALLINT(display_width=6), nullable=False),
    sa.Column('trial_duration', mysql.SMALLINT(display_width=6), nullable=False),
    sa.Column('trial_price', mysql.DECIMAL(precision=4, scale=4), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=4), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_recurring_transaction',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('order_recurring_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('reference', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('amount', mysql.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_shipment',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('order_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('shipping_courier_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('tracking_number', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('allowances', flask_authorize.mixins.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sellers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=125), nullable=False),
    sa.Column('lastName', sa.String(length=125), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('mobile', sa.String(length=25), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('confirmCode', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('mobile', sa.String(length=14), nullable=False),
    sa.Column('reg_time', sa.DateTime(), nullable=True),
    sa.Column('online', sa.String(length=1), nullable=False),
    sa.Column('activation', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('seller_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('model', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('sku', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('upc', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('ean', mysql.VARCHAR(length=14), nullable=False),
    sa.Column('jan', mysql.VARCHAR(length=13), nullable=False),
    sa.Column('isbn', mysql.VARCHAR(length=17), nullable=False),
    sa.Column('mpn', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('location', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('quantity', mysql.INTEGER(display_width=4), nullable=False),
    sa.Column('stock_status_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('image', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('manufacturer_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('shipping', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('price', mysql.DECIMAL(precision=15, scale=4), nullable=False),
    sa.Column('points', mysql.INTEGER(display_width=8), nullable=False),
    sa.Column('tax_class_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_available', sa.DATE(), nullable=False),
    sa.Column('weight', mysql.DECIMAL(precision=15, scale=8), nullable=False),
    sa.Column('weight_class_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('length', mysql.DECIMAL(precision=15, scale=8), nullable=False),
    sa.Column('width', mysql.DECIMAL(precision=15, scale=8), nullable=False),
    sa.Column('height', mysql.DECIMAL(precision=15, scale=8), nullable=False),
    sa.Column('length_class_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('subtract', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('minimum', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('sort_order', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('viewed', mysql.INTEGER(display_width=5), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('date_modified', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_group',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('product_description',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('language_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.INTEGER(display_width=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('tag', mysql.TEXT(), nullable=False),
    sa.Column('meta_title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('meta_description', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('meta_keyword', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_description')
    op.drop_table('user_role')
    op.drop_table('user_group')
    op.drop_table('products')
    op.drop_table('users')
    op.drop_table('sellers')
    op.drop_table('roles')
    op.drop_table('order_shipment')
    op.drop_table('order_recurring_transaction')
    op.drop_table('order_recurring')
    op.drop_table('order_product')
    op.drop_table('order_option')
    op.drop_table('order_history')
    op.drop_table('order')
    op.drop_table('language')
    op.drop_table('groups')
    op.drop_table('customer_wishlist')
    op.drop_table('customer_transaction')
    op.drop_table('customer_search')
    op.drop_table('customer_reward')
    op.drop_table('customer_online')
    op.drop_table('customer_login')
    op.drop_table('customer_ip')
    op.drop_table('customer_history')
    op.drop_table('customer_group_description')
    op.drop_table('customer_group')
    op.drop_table('customer_approval')
    op.drop_table('customer_affiliate')
    op.drop_table('customer_activity')
    op.drop_table('customer')
    op.drop_table('category_to_store')
    op.drop_table('category_to_layout')
    op.drop_table('category_to_google_product_category')
    op.drop_table('category_path')
    op.drop_table('category_filter')
    op.drop_table('category')
    op.drop_table('cart')
    # ### end Alembic commands ###
