"""Changed product_description.name from integer to varchar

Revision ID: e8d0583434b2
Revises: 8ccc1a33c37d
Create Date: 2023-03-01 17:53:01.879388

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8d0583434b2'
down_revision = '8ccc1a33c37d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_description',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('language_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('tag', mysql.TEXT(), nullable=False),
    sa.Column('meta_title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('meta_description', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('meta_keyword', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.alter_column('cart', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)
    op.alter_column('order_option', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)
    op.alter_column('order_product', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_product', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('order_option', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.alter_column('cart', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
    op.drop_table('product_description')
    # ### end Alembic commands ###
